### ISSUE TITLE
No network showing

### ISSUE THREAD

**Issue by minyaza** [Phoenix1747/RouteryPi#3]
I used the install script. did a reboot and no ap showing up on my other devices.
using latest Raspbian stretch
Using Rp3b+
`
  # Bridge mode
  bridge=br0

  # Networking interface
  interface=wlan0

  # WiFi configuration
  ssid=xxxx
  channel=1
  hw_mode=g
  country_code=AU
  ieee80211n=1
  ieee80211d=1
  wmm_enabled=1

  # WiFi security
  auth_algs=1
  wpa=2
  wpa_key_mgmt=WPA-PSK
  rsn_pairwise=CCMP
  wpa_passphrase=password`

**Comment by NuclearPhoenixx** [comment]
Hi, can you please post the full contents of these files `/etc/hostapd/hostapd.conf`, `/etc/network/interfaces` and `/etc/default/hostapd`. Oh and of course please don't forget to delete the password before uploading.

**Comment by minyaza** [comment]
not sure how to upload stuff, but here is a zip.

`

[routery.zip](https://github.com/Phoenix1747/RouteryPi/files/2822204/routery.zip)

`

**Comment by minyaza** [comment]
> pi@raspberrypi:~ $ sudo hostapd /etc/hostapd/hostapd.conf
Configuration file: /etc/hostapd/hostapd.conf
Line 2: invalid line '  # Bridge mode'
Line 3: unknown configuration item '  bridge'
Line 5: invalid line '  # Networking interface'
Line 6: unknown configuration item '  interface'
Line 8: invalid line '  # WiFi configuration'
Line 9: unknown configuration item '  ssid'
Line 10: unknown configuration item '  channel'
Line 11: unknown configuration item '  hw_mode'
Line 12: unknown configuration item '  country_code'
Line 13: unknown configuration item '  ieee80211n'
Line 14: unknown configuration item '  ieee80211d'
Line 15: unknown configuration item '  wmm_enabled'
Line 17: invalid line '  # WiFi security'
Line 18: unknown configuration item '  auth_algs'
Line 19: unknown configuration item '  wpa'
Line 20: unknown configuration item '  wpa_key_mgmt'
Line 21: unknown configuration item '  rsn_pairwise'
Line 22: unknown configuration item '  wpa_passphrase'
Line 23: invalid line '  '
19 errors found in configuration file '/etc/hostapd/hostapd.conf'
Failed to set up interface with /etc/hostapd/hostapd.conf
Failed to initialize interface

**Comment by minyaza** [comment]
Figured it out.. The hostapd.cof had 2 spaces on each line before the text and also and extra line on the bottom of the file... if i had of done the manual install, it would have worked fine.
