### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MikroMacaroni** [Phoenix1747/RouteryPi#5]
Nothing is appearing on available networks please help.

**Comment by NuclearPhoenixx** [comment]
So did you follow the instructions one by one and installed all needed packages correctly? What do your config files look like?

**Comment by MikroMacaroni** [comment]
# Bridge mode
bridge=br0

# Networking interface
interface=wlan0

# WiFi configuration
ssid=PIROUTER
channel=1
hw_mode=g
country_code=US
ieee80211n=1
ieee80211d=1
wmm_enabled=1

# WiFi security
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=cantshowpassword

**Comment by NuclearPhoenixx** [comment]
So how do `/etc/network/interfaces` and `sudo nano /etc/default/hostapd` look like? And have you installed `hostapd bridge-utils`?

**Comment by MikroMacaroni** [comment]
interfaces file : 
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
# source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

# Ethernet
auto eth0
allow-hotplug eth0
iface eth0 inet manual

# WiFi
auto wlan0
allow-hotplug wlan0
iface wlan0 inet manual
wireless-power off

# Bridge
auto br0
iface br0 inet dhcp
bridge_ports eth0 wlan0
bridge_fd 0
bridge_stp off

**Comment by MikroMacaroni** [comment]
/etc/default/hostapd file : 
# Defaults for hostapd initscript
#
# See /usr/share/doc/hostapd/README.Debian for information about alternative
# methods of managing hostapd.
#
# Uncomment and set DAEMON_CONF to the absolute path of a hostapd configuration
# file and hostapd will be started during system boot. An example configuration
# file can be found at /usr/share/doc/hostapd/examples/hostapd.conf.gz
#
#DAEMON_CONF=""

# Additional daemon options to be appended to hostapd command:-
#       -d   show more debug messages (-dd for even more)
#       -K   include key data in debug messages
#       -t   include timestamps in some debug messages
#
# Note that -B (daemon mode) and -P (pidfile) options are automatically
# configured by the init.d script and must not be added to DAEMON_OPTS.
#
#DAEMON_OPTS=""

RUN_DAEMON=yes
DAEMON_CONF="/etc/hostapd/hostapd.conf"

**Comment by NuclearPhoenixx** [comment]
Ok, thank you. So have you also connected the pi to a working router with dhcp via it's ethernet interface?

**Comment by MikroMacaroni** [comment]
Yes.

**Comment by NuclearPhoenixx** [comment]
And you also got the latest package versions installed via `sudo apt update && sudo apt dist-upgrade`, I guess?

**Comment by MikroMacaroni** [comment]
Yes.

**Comment by NuclearPhoenixx** [comment]
What Pi do you work with here? Like a new Pi with builtin WLAN or a dongle? And have you also double-checked that it does not show up? Looks fine to me, except maybe some config settings may have changed after a package update.

**Comment by NuclearPhoenixx** [comment]
And have you also rebooted your pi once before trying?

**Comment by MikroMacaroni** [comment]
I work with a Raspberry Pi 3B+ and Yes I double checked. Yes I rebooted my pi once before trying.

**Comment by MikroMacaroni** [comment]
I updated the Packages before I Set it up.

**Comment by NuclearPhoenixx** [comment]
Ok thanks, that's really strange. Can you also please check the wifi with another device. Only possible thing that comes in my mind is that there may have been breaking changes which require some new configs. Though I currently don't have a Pi at hand on which I could test it. So you're welcomed to help debug :P

**Comment by MikroMacaroni** [comment]
I did that. It did not work either. And Your welcome! 😃

**Comment by SaengerItsWar** [comment]
Hello the funny thing is i have the same bug as @Skylark011 with the same configurations and also double checked it and restarted my Raspberry Pi 3 b+

My /etc/hostapd/hostapd.conf :
```
# Bridge mode
bridge=br0

# Networking interface
interface=wlan0

# WiFi configuration
ssid=RaspyRouter
channel=1
hw_mode=g
country_code=DE
ieee80211n=1
ieee80211d=1
wmm_enabled=1

# WiFi security
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=*************
```

My /etc/network/interfaces :
```
# interfaces(5) file used by ifup(8) and ifdown(8)

# Please note that this file is written to be used with dhcpcd
# For static IP, consult /etc/dhcpcd.conf and 'man dhcpcd.conf'

# Include files from /etc/network/interfaces.d:
#source-directory /etc/network/interfaces.d
auto lo
iface lo inet loopback

# Ethernet
auto eth0
allow-hotplug eth0
iface eth0 inet manual

# WiFi
auto wlan0
allow-hotplug wlan0
iface wlan0 inet manual
wireless-power off

# Bridge
auto br0
iface br0 inet dhcp
bridge_ports eth0 wlan0
bridge_fd 0
bridge_stp off
```

and My /etc/default/hostapd :
```
# Defaults for hostapd initscript
#
# See /usr/share/doc/hostapd/README.Debian for information about alternative
# methods of managing hostapd.
#
# Uncomment and set DAEMON_CONF to the absolute path of a hostapd configuration
# file and hostapd will be started during system boot. An example configuration
# file can be found at /usr/share/doc/hostapd/examples/hostapd.conf.gz
#
#DAEMON_CONF=""

# Additional daemon options to be appended to hostapd command:-
#       -d   show more debug messages (-dd for even more)
#       -K   include key data in debug messages
#       -t   include timestamps in some debug messages
#
# Note that -B (daemon mode) and -P (pidfile) options are automatically
# configured by the init.d script and must not be added to DAEMON_OPTS.
#
#DAEMON_OPTS=""
RUN_DAEMON=yes
DAEMON_CONF="/etc/hostapd/hostapd.conf"
```

**Comment by SaengerItsWar** [comment]
oh and also the Newest version of the Raspbian Stretch reposity

**Comment by SaengerItsWar** [comment]
i found out that the hostapd.conf is working correctly but on the newest version of the raspbian stretch is the hostapd is not starting automatikly but if i start the hostapd manualy (sudo hostapd /etc/hostapd/hostapd.conf) it works fine.
![raspberryrouter](https://user-images.githubusercontent.com/13980351/54081181-acd1c380-4300-11e9-9a57-fd61e9253eeb.PNG)

**Comment by SaengerItsWar** [comment]
there is something wrong with the init script so i found a workaround for now 
```
To use the ifupdown method, the path to hostapd configuration file can
be specified in a network interfaces configuration stanza in
/etc/network/interfaces like so:

iface eth1 inet static
        hostapd /etc/hostapd/hostapd.conf
        ...

The hostapd process will be started in the pre-up phase of ifup, and be
terminated in the post-down phase of ifdown.
```
source: /usr/share/doc/hostapd/README.Debian

and it works correct

**Comment by MikroMacaroni** [comment]
Ah, hah! I figured it out. I just used rc.local to start the hostapd on boot. 
Here is the code : 
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other # value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

# Print the IP address
_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

sudo hostapd /etc/hostapd/hostapd.conf
exit 0

**Comment by NuclearPhoenixx** [comment]
Thanks for your effort, what output do you get by typing `sudo service hostapd start` and `sudo service hostapd status`?

**Comment by MikroMacaroni** [comment]
pi@PROJECTROUTERPI:~ $ sudo service hostapd start
Failed to start hostapd.service: Unit hostapd.service is masked.

**Comment by MikroMacaroni** [comment]
pi@PROJECTROUTERPI:~ $ sudo service hostapd status
● hostapd.service
   Loaded: masked (/dev/null; bad)
   Active: inactive (dead)

**Comment by NuclearPhoenixx** [comment]
Ok, then maybe give this a try:

```
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
sudo systemctl start hostapd
```

Found a similar problem here: https://github.com/raspberrypi/documentation/issues/1018

**Comment by MikroMacaroni** [comment]
Now it's broken again.

**Comment by MikroMacaroni** [comment]
When it's masked, it starts up on boot

**Comment by NuclearPhoenixx** [comment]
Oh god. I have no idea what's happening.

**Comment by EthanDarling8** [comment]
Using this as @Phoenix1747 suggested works for me:

`sudo systemctl unmask hostapd`
`sudo systemctl enable hostapd`
`sudo systemctl start hostapd`
`sudo reboot`

I'm using a raspberry pi 3B+ without a wifi adapter, just ethernet and it's own built in wifi. Be patient as it reboots as well, it took a couple minutes for me. Also i'm using the latest stretch lite and logging in headless if that makes a difference.

**Comment by NuclearPhoenixx** [comment]
So to get back to the issue, did it work for you too @Skylark011 ?

**Comment by NuclearPhoenixx** [comment]
OK, I'm closing this for now since it looks like it's solved. If you still have this problem please reopen this issue.
