### ISSUE TITLE
Hostapd fixing autostart issue

### ISSUE THREAD

**Issue by justkowal** [Phoenix1747/RouteryPi#6]
I followed instructions and my wifi AP is not autostarting when i tried to fix that with solution in the article this happened:
`pi@raspberrypi:~ $ sudo systemctl start hostapd
Job for hostapd.service failed because the control process exited with error cod                                                                    e.
See "systemctl status hostapd.service" and "journalctl -xe" for details.
pi@raspberrypi:~ $ systemctl status hostapd service
● hostapd.service - Advanced IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP Authent
   Loaded: loaded (/lib/systemd/system/hostapd.service; enabled; vendor preset:
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-05-15 07
  Process: 882 ExecStart=/usr/sbin/hostapd -P /run/hostapd.pid -B $DAEMON_OPTS $

 raspberrypi systemd[1]: hostapd.service: Control process exited,
 raspberrypi systemd[1]: Failed to start Advanced IEEE 802.11 AP
 raspberrypi systemd[1]: hostapd.service: Unit entered failed sta
 raspberrypi systemd[1]: hostapd.service: Failed with result 'exi
Unit service.service could not be found.
lines 1-10/10 (END)
● hostapd.service - Advanced IEEE 802.11 AP and IEEE 802.1X/WPA/WPA2/EAP Authenticator
   Loaded: loaded (/lib/systemd/system/hostapd.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Wed 2019-05-15 07:19:54 BST; 1s a
  Process: 882 ExecStart=/usr/sbin/hostapd -P /run/hostapd.pid -B $DAEMON_OPTS ${DAEMON_CONF} (c

 raspberrypi systemd[1]: hostapd.service: Control process exited, code=exited sta
 raspberrypi systemd[1]: Failed to start Advanced IEEE 802.11 AP and IEEE 802.1X/
 raspberrypi systemd[1]: hostapd.service: Unit entered failed state.
raspberrypi systemd[1]: hostapd.service: Failed with result 'exit-code'.
Unit service.service could not be found.`

**Comment by justkowal** [comment]
I think that i have a solution!
 sudo hostapd -B /etc/hostapd/hostapd.conf

**Comment by justkowal** [comment]
nope it still does not work!
 
Configuration file: /etc/hostapd/hostapd.conf
nl80211: Driver does not support authentication/association or connect commands
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED
hostapd_free_hapd_data: Interface wlan0 wasn't started

**Comment by NuclearPhoenixx** [comment]
Do you know why it's saying ``nl80211: Driver does not support authentication/association or connect commands``? Are you using the Raspis internal WLAN?

**Comment by EthanDarling8** [comment]
From the looks of these lines,
> nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
>  wlan0: AP-DISABLED

It seems like you are using an external WiFi adapter like @Phoenix1747 was questioning. Wlan0 should be your Pi's internal WLAN. If you are using an external adapter, not all WiFi adapters will work. If you aren't using an external adapter, what does your hostapd.conf file look like?

**Comment by NuclearPhoenixx** [comment]
Can you give me some more detail, @hopkuba?

**Comment by NuclearPhoenixx** [comment]
Closing due to lack of detail. Please re-open if needed.
