### ISSUE TITLE
Configuring different ip range for connected devices

### ISSUE THREAD

**Issue by nikhil1232** [Phoenix1747/RouteryPi#7]
How do I assign a different subnet or ip range for all the devices connected to my access point.

**Comment by NuclearPhoenixx** [comment]
Unfortunately, you can't do it with this tutorial.

I only cover how to make an access point here, which acts as a network bridge. This requires you to use an external router with all the DHCP and network setup. You'll need to adjust the settings at the router that you plugged your Pi into. However, you can also set your own DHCP and DNS servers up and use this for your network connection. This is a completely other tutorial, though, and much more complicated than this.

**Comment by NuclearPhoenixx** [comment]
Any ideas and pull requests are greatly appreciated for any who read this, tough. No need to limit the tutorial and stay at access point setups ;)

**Comment by NuclearPhoenixx** [comment]
Closed, hope I answered your question.
