### ISSUE TITLE
Poll: Raspberry Pi 4 Performance

### ISSUE THREAD

**Issue by NuclearPhoenixx** [Phoenix1747/RouteryPi#8]
Tested networking performance with the new Raspberry Pi 4? Please comment some speedtests or other test results! I'm really curious :)

**Comment by rishi-kumar-verma** [comment]
yes, it is working fine but NanoPC-T4 internet stop working. any suggestion ?

**Comment by NuclearPhoenixx** [comment]
I don't know what a NanoPC-T4 is. If it's related in any way to this project (raspberry pi!) please open a new issue.

**Comment by EthanDarling8** [comment]
> yes, it is working fine but NanoPC-T4 internet stop working. any suggestion ?

The NanoPC-T4 is not a raspberry pi but does run Linux as far as I am aware of. Seems unrelated.

**Comment by NuclearPhoenixx** [comment]
Reopened because it's still interesting to me. Have to test it with my Pi4.

**Comment by NuclearPhoenixx** [comment]
Hint has been added to the README, will test the speeds eventually.
